const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let chatHistory=[];
$$("nav button").forEach(b=>b.onclick=()=>{$$("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".view").forEach(v=>v.classList.remove("active"));$("#"+b.dataset.v).classList.add("active");if(b.dataset.v==="history")loadHistory()});
$("#claimTab").onclick=()=>switchMode(false);$("#urlTab").onclick=()=>switchMode(true);
function switchMode(url){$("#claimTab").classList.toggle("active",!url);$("#urlTab").classList.toggle("active",url);$("#check").classList.toggle("hide",url);$("#analyze").classList.toggle("hide",!url);$("#input").placeholder=url?"https://example.com/news/article":"Paste a claim, news statement, article URL, or social-media post..."}
function prefs(){return{content_mode:$("#contentMode").value,detail:$("#detail").value,audience:$("#audience").value,source_preference:$("#sourcePref").value,region:$("#region").value,language:$("#language").value}}
async function post(path,body){const r=await fetch("/api"+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||"Request failed");return d}
$("#check").onclick=async()=>{const text=$("#input").value.trim();if(!text)return;await run("/fact-check",{text,...prefs()},renderResult)};
$("#analyze").onclick=async()=>{const url=$("#input").value.trim();if(!url)return;await run("/fact-check/url",{url,text:url,...prefs()},renderArticle)};
async function run(path,body,render){$("#status").textContent="Checking…";$("#result").innerHTML="";try{render(await post(path,body))}catch(e){$("#result").innerHTML='<div class="warning">'+esc(e.message)+"</div>"}finally{$("#status").textContent=""}}
function esc(x=""){return String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function sources(a){return (a||[]).map((x,i)=>'<div class="source"><b>['+(i+1)+"] "+esc(x.title)+"</b><small>"+esc(x.publisher)+" · "+esc(x.date||"Date unavailable")+" · "+esc(x.source_type)+"</small><br><a href='"+esc(x.url)+"' target='_blank' rel='noopener'>Open source →</a></div>").join("")||'<p class="muted">No independently verifiable sources were found.</p>'}
function evidence(a){return (a||[]).map(x=>'<div class="item"><b>'+esc(x.title||x.publisher||"Evidence")+"</b><p>"+esc(x.excerpt)+"</p><a href='"+esc(x.url)+"' target='_blank' rel='noopener'>Open source →</a></div>").join("")||'<p class="muted">No source evidence was supplied.</p>'}
function renderResult(d){const sections=(d.report_sections||[]).map(x=>"<div class='item'>"+esc(x)+"</div>").join("");$("#result").innerHTML='<div class="resultcard"><div class="muted">CLAIM ANALYSIS REPORT · '+esc(d.content_type)+"</div><h2>"+esc(d.report_title||"Fact Check Analysis Report")+"</h2><div class='verdict'>"+esc(d.verdict)+"</div><p>Assessment confidence: <b>"+d.confidence+"%</b></p><button class='secondary' onclick='shareResult("+d.id+")'>Share Result</button><div class='section'><h3>Input</h3><p>"+esc(d.claim)+"</p></div><div class='section'><h3>Executive summary</h3><p>"+esc(d.summary)+"</p></div>"+(sections?"<div class='section'><h3>Analysis report</h3>"+sections+"</div>":"")+(d.claims_checked?.length?"<div class='section'><h3>Claims checked</h3>"+d.claims_checked.map((c,i)=>"<div class='item'><b>"+(i+1)+". "+esc(c.claim)+"</b><p>"+esc(c.verdict)+" · "+c.confidence+"%</p><p>"+esc(c.summary)+"</p></div>").join("")+"</div>":"")+"<div class='section'><h3>Supporting evidence</h3>"+evidence(d.supporting_evidence)+"</div><div class='section'><h3>Contradicting evidence</h3>"+evidence(d.contradicting_evidence)+"</div><div class='section'><h3>Context</h3><p>"+esc(d.context)+"</p></div><div class='section'><h3>Assessment reasoning</h3><p>"+esc(d.reasoning)+"</p></div><div class='section'><h3>Sources</h3>"+sources(d.sources)+"</div>"+(d.uncertainties?.length?"<div class='warning'><b>Uncertainty</b><ul>"+d.uncertainties.map(x=>"<li>"+esc(x)+"</li>").join("")+"</ul></div>":"")+"<div class='section'><small class='muted'>Last checked: "+esc(d.last_checked)+"</small></div></div>"} 
function renderArticle(d){$("#result").innerHTML='<div class="resultcard"><div class="muted">ARTICLE FACT CHECK</div><h2>'+esc(d.article_title||"Article")+"</h2><div class='verdict'>"+esc(d.overall_verdict)+"</div><p>Assessment confidence: <b>"+d.overall_confidence+"%</b></p><button class='secondary' onclick='shareResult("+d.id+")'>Share Result</button><div class='section'><h3>Overall assessment</h3><p>"+esc(d.summary)+"</p></div><div class='section'><h3>Claims checked</h3>"+(d.claims_checked||[]).map((c,i)=>"<div class='item'><b>"+(i+1)+". "+esc(c.claim)+"</b><p>"+esc(c.verdict)+" · "+c.confidence+"%</p><p>"+esc(c.summary)+"</p></div>").join("")+"</div><div class='section'><h3>Sources</h3>"+sources(d.sources)+"</div></div>"}
function shareResult(id){const u=location.origin+"/share/"+id;navigator.clipboard?.writeText(u);alert("Share link copied: "+u)}
$("#send").onclick=async()=>{const m=$("#chatInput").value.trim();if(!m)return;add("user",m);$("#chatInput").value="";try{const d=await post("/chat",{message:m,history:chatHistory});chatHistory.push({role:"user",content:m},{role:"assistant",content:d.reply});add("ai",d.reply)}catch(e){add("ai","We couldn't complete this request right now.")}}
function add(role,text){const d=document.createElement("div");d.className="bubble "+role;d.textContent=text;$("#chatLog").appendChild(d)}
async function loadHistory(){try{const q=encodeURIComponent($("#hq").value);const d=await fetch("/api/history?q="+q).then(r=>r.json());$("#historyList").innerHTML=d.items.map(x=>'<div class="history"><button class="secondary" onclick="openHistory('+x.id+')">'+esc(x.title)+"</button> <b>"+esc(x.verdict)+"</b> · "+x.confidence+"% <button class='secondary' onclick='deleteHistory("+x.id+")'>Delete</button></div>").join("")||'<p class="muted">No fact checks yet.</p>'}catch(e){$("#historyList").textContent="Unable to load history."}}
async function openHistory(id){const d=await fetch("/api/history/"+id).then(r=>r.json());$(".view.active").classList.remove("active");$("#fact").classList.add("active");renderResult(d)}
async function deleteHistory(id){await fetch("/api/history/"+id,{method:"DELETE"});loadHistory()}$("#hq").oninput=loadHistory;$("#clear").onclick=async()=>{if(confirm("Clear all history?")){await fetch("/api/history",{method:"DELETE"});loadHistory()}};
for(const id of ["detail","audience","sourcePref","region","language"]){const k="fc_"+id,v=localStorage.getItem(k);if(v)$("#"+id).value=v;$("#"+id).onchange=e=>localStorage.setItem(k,e.target.value)}
